# Generated by Django 5.1.3 on 2024-12-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('RAZORPAY', 'RAZORPAY'), ('COD', 'COD'), ('QUBITS_WALLET', 'QUBITS_WALLET')], max_length=25),
        ),
    ]
