# Generated by Django 5.1.3 on 2024-12-11 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2c8e628f-7ccb-465c-8582-04fedb201d85'), primary_key=True, serialize=False),
        ),
    ]
